import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
import './globals.css';
import { GlobalHeader, GlobalFooter } from '@/components';

const notoSans = Noto_Sans({
  variable: '--font-noto-sans',
  subsets: ['latin'],
  weight: ['400', '500', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${notoSans.className} bg-background text-text-primary grid min-h-screen grid-rows-[auto_1fr_auto] antialiased`}
      >
        <GlobalHeader />
        <div className="mx-auto w-full max-w-5xl p-6">{children}</div>
        <GlobalFooter />
      </body>
    </html>
  );
}
